# Generated by Django 2.2.2 on 2021-05-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('rewardpoints', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
